"""zall.cli.init_wizard — Interactive /init project setup wizard (P3-b).

Replaces the old 4-file template generator with an interactive Q&A flow
that asks about project type, tech stack, testing, MCP servers, and model.

Uses prompt_toolkit for interactive prompts (falls back to plain input).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

try:
    from prompt_toolkit import prompt as ptk_prompt
    from prompt_toolkit.shortcuts import yes_no_dialog, radiolist_dialog, input_dialog
    _HAS_PTK = True
except ImportError:
    _HAS_PTK = False


# ──────────────────────────────────────────────────────────────────────────
# Template generators
# ──────────────────────────────────────────────────────────────────────────


def _rules_toml(project_type: str, test_framework: str) -> str:
    """Generate rules.toml based on project type."""
    deny_commands = ["rm -rf", "git push --force", "git reset --hard"]
    if project_type in ("python",):
        deny_commands.append("pip uninstall")
    elif project_type in ("rust",):
        deny_commands.append("cargo uninstall")

    # 渲染 TOML 数组 (非 Python repr — 避免 B1 臭名昭著的 f-string list bug)
    deny_commands_toml = "[" + ", ".join(f'"{c}"' for c in deny_commands) + "]"

    test_comment = ""
    if test_framework:
        test_comment = f"# Test framework: {test_framework}"
        if test_framework == "pytest":
            test_comment += "\n# pytest run: `python -m pytest tests/`"

    return f"""\
# zall project rules (§4.2.1 context_judge — user-local Authority rules)
# Auto-generated by `zall init` (project type: {project_type})

[allow]
# Tools/actions that skip confirmation (whitelist)
# WARNING: only add trusted, read-only tools here
tools = ["read_file", "list_dir", "grep", "glob"]

[deny]
# Tools/actions that require explicit override + audit
tools = []
commands = {deny_commands_toml}

[settings]
# Project-level default judge mode
#   none   = undecidable (default, honest fallback)
#   system = run tests to determine task completion
judge = "none"

[compactor]
# Context compression settings (optional)
# strategy: "model_summary" | "truncation"
# threshold: minimum messages before compaction
strategy = "model_summary"
threshold = 8
"""


def _agents_md(project_type: str, description: str) -> str:
    """Generate AGENTS.md with project-specific guidance."""
    tech_stack_hints = {
        "python": "Python (>=3.10), pytest, ruff, mypy",
        "javascript": "Node.js, npm/yarn/pnpm, Jest/Vitest",
        "typescript": "TypeScript, Node.js, npm/yarn/pnpm, Jest/Vitest",
        "rust": "Rust, cargo, rustfmt, clippy",
        "go": "Go, gofmt, go mod",
        "generic": "",
    }
    hint = tech_stack_hints.get(project_type, "")

    return f"""\
# AGENTS.md — zall project memory (§9.4)
#
# > Project-level memory: agent can READ this; modifying it requires
# > greylist confirmation (confirm_gate + audit).
# > The agent must NEVER modify Authority rules via AGENTS.md.

## Project Overview
{description or f"A {project_type} project"}

## Tech Stack
{hint or "(describe your tech stack here)"}

## Conventions
- Code style: (describe formatting / linting rules)
- Testing: (describe test conventions)
- Branch strategy: (main, develop, feature branches)
"""


def _mcp_toml() -> str:
    """Generate MCP config template with examples."""
    return """\
# MCP server registry (§9.2.11)
#
# Add MCP servers below. Each server is started as a subprocess.
# Tools from MCP servers default to greylist (require user confirmation).
#
# Pre-built MCP servers (install with npm/npx):
#   @modelcontextprotocol/server-filesystem  — file read/write/search
#   @modelcontextprotocol/server-github      — GitHub API (issues, PRs, repos)
#   @modelcontextprotocol/server-brave-search — web search
#   @modelcontextprotocol/server-fetch       — HTTP fetch
#   @modelcontextprotocol/server-puppeteer   — browser automation
#
# Example: Filesystem server
# [[servers]]
# name = "filesystem"
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem", "."]
#
# Example: GitHub server (set GITHUB_TOKEN env var)
# [[servers]]
# name = "github"
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-github"]
# env = { GITHUB_TOKEN = "${GITHUB_TOKEN}" }
#
# Example: Web search
# [[servers]]
# name = "search"
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-brave-search"]
# env = { BRAVE_API_KEY = "${BRAVE_API_KEY}" }
"""


def _skills_toml() -> str:
    """Generate skills template."""
    return """\
# zall skills — reusable Goal templates (§9.2.7)
#
# Skills are Goal-level templates: they define a reusable intent.
# {input} placeholders are filled from the /skill command argument.
# Skills do NOT bypass confirm_gate (§9.2.7 anti-smuggling).

[[skills]]
name = "explain"
description = "Explain code or concepts"
prompt = "Explain {input} in detail. Cover what it does, why it exists, and any trade-offs."

[[skills]]
name = "review"
description = "Review code changes"
prompt = "Review {input} for bugs, style issues, and security concerns. Suggest concrete improvements."
"""


# ──────────────────────────────────────────────────────────────────────────
# Interactive wizard
# ──────────────────────────────────────────────────────────────────────────


def _ask_ptk(label: str, default: str = "") -> str:
    """Use prompt_toolkit for interactive input."""
    try:
        return ptk_prompt(f"  {label}: ", default=default)
    except (EOFError, KeyboardInterrupt):
        return default or ""


def _ask_plain(label: str, default: str = "") -> str:
    """Fallback to plain input()."""
    try:
        val = input(f"  {label} [{default}]: ").strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        return default or ""


def init_wizard(out: Any, cwd: str | None = None) -> None:
    """Interactive project initialization wizard (P3-b).

    Replaces the old _cmd_init 4-file template generator with a
    Q&A flow that asks about project type, tech stack, and preferences.
    """
    base = (Path(cwd) if cwd else Path.cwd()) / ".zall"
    if base.exists() and any(base.iterdir()):
        out.write("  .zall/ already exists and is not empty.\n")
        out.write("  Delete .zall/ first if you want to reinitialize.\n")
        return

    base.mkdir(parents=True, exist_ok=True)
    ask = _ask_ptk if _HAS_PTK else _ask_plain

    out.write("  zall project setup wizard\n")
    out.write("  (press Enter to accept defaults)\n\n")

    # ── Step 1: Project type ──
    project_type = ask("Project type", "python")
    if not project_type:
        project_type = "python"
    project_type = project_type.strip().lower()

    # ── Step 2: Description ──
    description = ask("Short project description", "My zall project")

    # ── Step 3: Test framework ──
    test_hints = {
        "python": "pytest",
        "javascript": "jest",
        "typescript": "jest",
        "rust": "cargo test",
        "go": "go test",
    }
    default_test = test_hints.get(project_type, "")
    test_framework = ask("Test framework", default_test)

    # ── Step 4: Model preference ──
    model = ask("Default model (e.g., gpt-4o, claude-sonnet-4)", "gpt-4o")

    # ── Step 5: Write files ──
    files_created = []

    # rules.toml
    rules_content = _rules_toml(project_type, test_framework)
    (base / "rules.toml").write_text(rules_content, encoding="utf-8")
    files_created.append("rules.toml")

    # AGENTS.md
    agents_content = _agents_md(project_type, description)
    (base / "AGENTS.md").write_text(agents_content, encoding="utf-8")
    files_created.append("AGENTS.md")

    # mcp.toml
    (base / "mcp.toml").write_text(_mcp_toml(), encoding="utf-8")
    files_created.append("mcp.toml")

    # skills.toml
    (base / "skills.toml").write_text(_skills_toml(), encoding="utf-8")
    files_created.append("skills.toml")

    # config.toml (persist model choice)
    config_path = Path.home() / ".zall" / "config.toml"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_content = f"""[auth]
# API key (or set ZALL_API_KEY env var)
api_key = ""

[model]
	name = "{model}"

[settings]
stream = true
verbose = false
"""
    config_path.write_text(config_content, encoding="utf-8")
    files_created.append("~/.zall/config.toml")

    # O5: TrustAnchor init化 (生成 ed25519 key + anchor指纹)
    try:
        from zall.core.verifiability import FileTrustAnchor
        anchor = FileTrustAnchor()
        if anchor.anchor_id:
            out.write(f"  ✓ trust anchor initialized (id={anchor.anchor_id})\n")
            files_created.append("~/.zall/trust_anchor_key (ed25519)")
    except Exception as e:
        out.write(f"  · trust anchor setup skipped: {e}\n")

    # ── Summary ──
    out.write(f"\n  ✓ Initialized zall project config at {base}\n")
    for f in files_created:
        if f.startswith("~/"):
            out.write(f"    - {f}\n")
        else:
            out.write(f"    - .zall/{f}\n")
    out.write(f"\n  Project: {project_type.upper()}")
    if test_framework:
        out.write(f"  |  Test: {test_framework}")
    out.write(f"  |  Model: {model}\n")
    out.write("\n  Run 'zall' to start working.\n")